### ISSUE TITLE
Feature Request: hide notes

### ISSUE THREAD

**Issue by joeldierkes** [ntjess/typst-drafting#1]
Hey, I really like the package and the looks of the notes. :+1: 
It would be nice to have a way of suppressing/hiding the notes (something like latex `todonotes` [^1] disable feature). The overall idea would be to have a drafting and preview mode, where the drafting would show the notes and the preview would simply omit them. This would make it easier to create intermediate versions of a document for distribution without personal opinions and with the final formatting of the document. 

I am thinking of something like
```typescript
#hide_notes()
```
at the beginning of the document. This should also work for included files.

Note that the page parameters must somehow be updated too (to remove the margin).

Hope this is the right place and that I'm not imposing.

[^1]: http://tug.ctan.org/macros/latex/contrib/todonotes/todonotes.pdf

**Comment by ntjess** [comment]
This can now be accomplished by calling
```typst
#set-margin-note-defaults(..., hidden: true)
```

@joeldierkes Thanks for the feature idea!
