### ISSUE TITLE
Import Required in Every File

### ISSUE THREAD

**Issue by CronJorian** [ntjess/typst-drafting#13]
Not sure if this is intended, however, if your file structure looks like this:

├── main.typ <- imports drafting
└── chapters/
    ├── chapter1.typ
    └── chapter2.typ

The note commands can only be called from chapter1.typ or chapter2.typ if these import drafting too.
I did not find anything in the docs according to modular files.

If the required reimports are intentional, just close this issue, however I think it'd be more convenient to import it just once.

**Comment by ntjess** [comment]
This is an aspect of typst's design in general (imports are scoped to the file that imported them, not all of its children), so indeed it's not something that can be addressed in this package.

My workaround is to specify helper code in a `utils.typ` file, and then I just need to import `utils.typ: *` and I have access to the shorthand notation I can use in the child files.
