### ISSUE TITLE
Margin notes jump to next page.

### ISSUE THREAD

**Issue by SebastianJL** [ntjess/typst-drafting#8]
Possibly related to #5.

Sometimes margin notes jump to the next page, seemingly unwarrented.

![image](https://github.com/ntjess/typst-drafting/assets/11479035/ab03a34b-363b-4039-8f68-8ce30aeee28e)

My quickfix is 
```typst
#margin-note(dy:2cm)[margin note text]
```
But of course that `dy` value changes with every change I make.

**Comment by SebastianJL** [comment]
I have a new bug, I'll post it here. The note just goes off page, and I couldn't use `dy` or `dx` to correct that.
![image](https://github.com/ntjess/typst-drafting/assets/11479035/f52267e9-61b1-40a2-9765-dcf5866a0aea)

**Comment by ntjess** [comment]
Thanks for the report, but I'm having a difficult time reproducing the behavior:

```typst
#import "@preview/drafting:0.1.1": set-page-properties, margin-note

#let margin = (left: 2.5cm, right: 2.5cm)  // Increased margins for notes.
#set page(margin: margin, numbering: "1", number-align: center)
#set-page-properties(margin-left: margin.left, margin-right: margin.right)


#for ii in range(5) [
+ #lorem((ii + 1) * 3)#margin-note[test]#lorem((ii + 1)* 3)
]
```

![image](https://github.com/ntjess/typst-drafting/assets/23620506/534d2a6b-41e4-45d1-b2ed-938f693c2d62)

Any chance you are able to attach a MWE so I can debug more easily?

**Comment by SebastianJL** [comment]
Yes for sure

```typst
#import "@preview/drafting:0.1.1": margin-note, set-page-properties

#set text(font: "New Computer Modern", lang: "en")
#show par: set par(justify: true)

#let margin = (left: 2.5cm, right: 2.5cm)
#set page(margin: margin, numbering: "1", number-align: center)
#set-page-properties(margin-left: margin.left, margin-right: margin.right)

#lorem(100)#margin-note[Trying to replicate a certain problem.]
#lorem(50)#margin-note[I have no idea how it would happen.]
#lorem(200)#margin-note[But let's still try anyway.]
#lorem(200)#margin-note[But let's still try anyway.]
```

![image](https://github.com/ntjess/typst-drafting/assets/11479035/e11930c6-ebd2-4e66-a89d-cbcf984af8fe)

It doesn't look exactly the same, but it might be the same thing.

**Comment by SebastianJL** [comment]
@ntjess Hi, I just wanted to ask if the minimal example was at all helpful at finding the issue. Meanwhile I found more occasions where the note is placed in the wrong place.
![image](https://github.com/ntjess/typst-drafting/assets/11479035/62ac89c8-ddda-4bb6-a7d3-866fa46778d4)

**Comment by ntjess** [comment]
Thanks for the reproducible example! I've fixed the problem from the code you've given, is it possible to provide the source for your other error cases?

**Comment by SebastianJL** [comment]
Ah very cool. Thanks a lot. Yes I can give you the other cases, but only as full projects. It's not that large though. I'll have to do that later when I am on the computer.

**Comment by ntjess** [comment]
Thank you for sharing the code! The error occurs even in this simple case:
```typst
#import "typst-drafting/drafting.typ": margin-note, set-page-properties

#let margin = (left: 2.5cm, right: 2.5cm)  // Increased margins for notes.
#set page(margin: margin)
#set-page-properties(margin-left: margin.left, margin-right: margin.right)

c#margin-note[Insert reference]
+ B #margin-note[is this true?]

propagation happen.
#margin-note[s?]
```
![image](https://github.com/ntjess/typst-drafting/assets/23620506/71c1a30e-b451-4dc2-978c-2e615fffb8c6)

I will continue to investigate.

**Comment by SebastianJL** [comment]
Thanks this fixes all problems. It's sometimes a little weird when you have several large notes close in the text, because the lines start overlapping but I think it's worth it.
