### ISSUE TITLE
Line numbering

### ISSUE THREAD

**Issue by yochem** [ntjess/typst-drafting#9]
I'm currently working on having draft line numbers for paragraphs:

<img width="613" alt="image" src="https://github.com/ntjess/typst-drafting/assets/23235841/6f77f966-4c9c-4250-adae-7d8f653e8ed2">

There are still some known bugs, but nothing that can't be fixed. Would this be something that you would like to include in this project? It seems like a great addition to this package to me.

**Comment by ntjess** [comment]
I'm very interested in this feature, but I would want it to work the same way as preprints (numbering is associated with absolute page positions rather than text lines). This will allow it to work with images, headings, etc.

My first attempt was to `#set page(background: ...)` but this had too many edge cases preventing it from working. But that was awhile ago (typst 0.7 I think?), maybe the attempt would work better now.

In any case, if you submit a PR that adds numbering to the page itself, I'd be quite happy to merge the feature!

**Comment by ntjess** [comment]
```typst
#let numbered = layout(size => {
  style(styles => {
    let spacing = 1.2em
    let line-height = measure(v(spacing), styles).height
    set align(left + top)
    show: pad.with(left: 1em)
    box(height: 100%)[
      #for ii in range(int(calc.ceil(size.height / line-height))) {
        place(dy: spacing * ii, str(ii + 1))
      }
    ]
  })
})

#set page(margin: 0.8in, background: numbered)
```

Here is a start, I will need to troubleshoot to see if there are any problems.

![image](https://github.com/ntjess/typst-drafting/assets/23620506/25606f17-754e-4b30-94ea-b0c9e2867230)

**Comment by yochem** [comment]
I was thinking about that too, but then it might be ambiguous which number a line would have. Communicating it like "on the line that is between 9 and 10 you missed a comma" is probably not ideal. It is much simpler to implement though.

**Comment by yochem** [comment]
This is how my current solutions handles e.g. headings and tables:

<img width="782" alt="image" src="https://github.com/ntjess/typst-drafting/assets/23235841/8c39332c-6444-46c3-8850-c35790ead0bf">

We could improve this to number every element:

<img width="827" alt="image" src="https://github.com/ntjess/typst-drafting/assets/23235841/c1991f50-4563-47ef-8162-91e74b625ebc">

But it currently changes the spacing, which is of course not desired. I'll fix that.

**Comment by ntjess** [comment]
@yochem How does it handle figures, grids, column environments, etc.? If it is robust, I like the way it looks here: 
![](https://private-user-images.githubusercontent.com/23235841/290459742-8c39332c-6444-46c3-8850-c35790ead0bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI5MTc4ODcsIm5iZiI6MTcwMjkxNzU4NywicGF0aCI6Ii8yMzIzNTg0MS8yOTA0NTk3NDItOGMzOTMzMmMtNjQ0NC00NmMzLTg4NTAtYzM1NzkwZWFkMGJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjE4VDE2Mzk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNzhkZmI0Nzc0NTJiODEwNTI2MDg0YzcyZDQwNDk2ZDUxMzExMjUwYzNlYTc1MTE5MjNhNDY5NzQ1OGEzZDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6Tc6xxx4R4J1nZs3XEMzuY1djmRUEaJXoCbfMdxX4LM)

Things to check:
- [ ] List
- [ ] Grid
- [ ] `tablex` rowspanx
- [ ] Figure
- [ ] changing text size / font
- [ ] `place`d content
- [ ] We can add to this list as time progresses

**Comment by yochem** [comment]
<img width="534" alt="image" src="https://github.com/ntjess/typst-drafting/assets/23235841/c971e7dc-9104-4a50-9b83-68be4ed26b21">

- [x] List
- [ ] Grid
- [x] tablex rowspanx: It's okay-ish
- [ ] Figure: should we add line numbers here?
- [ ] changing text size / font: Weirdly doesn't work yet
- [ ] placed content: I don't think this should be supported, because placed content can be everywhere
- [ ] We can add to this list as time progresses: sure!

I also haven't fixed the weird spacing issue yet.

**Comment by ntjess** [comment]
Typst now provides this out of the box with `par.line(numbering: "1")` so I think this request can be closed. Unless it should retarget a different form of numbering?

**Comment by yochem** [comment]
No you're right, this can be closed.
